
"""Add music models

Revision ID: 3be68cf36e73
Revises: d55875a5c2eb
Create Date: 2025-11-29 12:08:11.051897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3be68cf36e73'
down_revision: Union[str, None] = 'd55875a5c2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('albums',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_index(op.f('ix_albums_title'), 'albums', ['title'], unique=False)
    op.create_table('musics',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False, comment='时长(秒)'),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musics_id'), 'musics', ['id'], unique=False)
    op.create_index(op.f('ix_musics_title'), 'musics', ['title'], unique=False)

    # Create playlists table
    op.create_table('playlists',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.create_index(op.f('ix_playlists_name'), 'playlists', ['name'], unique=False)
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)

    # Create playlist_songs table
    op.create_table('playlist_songs',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_songs_id'), 'playlist_songs', ['id'], unique=False)
    op.create_index(op.f('ix_playlist_songs_playlist_id'), 'playlist_songs', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_songs_music_id'), 'playlist_songs', ['music_id'], unique=False)

    # Create interaction_type_enum
    interaction_type_enum = postgresql.ENUM('PLAY', 'LIKE', 'SKIP', name='interaction_type_enum', create_type=False)
    interaction_type_enum.create(op.get_bind(), checkfirst=True)

    # Create interactions table
    op.create_table('interactions',
    sa.Column('user_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', postgresql.ENUM('PLAY', 'LIKE', 'SKIP', name='interaction_type_enum', create_type=False), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_interactions_music_id'), 'interactions', ['music_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop interactions table and enum
    op.drop_index(op.f('ix_interactions_music_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    postgresql.ENUM(name='interaction_type_enum').drop(op.get_bind(), checkfirst=True)

    # Drop playlist_songs table
    op.drop_index(op.f('ix_playlist_songs_music_id'), table_name='playlist_songs')
    op.drop_index(op.f('ix_playlist_songs_playlist_id'), table_name='playlist_songs')
    op.drop_index(op.f('ix_playlist_songs_id'), table_name='playlist_songs')
    op.drop_table('playlist_songs')

    # Drop playlists table
    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_name'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_table('playlists')

    op.drop_index(op.f('ix_musics_title'), table_name='musics')
    op.drop_index(op.f('ix_musics_id'), table_name='musics')
    op.drop_table('musics')
    op.drop_index(op.f('ix_albums_title'), table_name='albums')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###