"""创建后端数据库 v1 版本

Revision ID: 8729e0b26799
Revises: 
Create Date: 2026-03-15 20:18:33.932075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8729e0b26799'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composers_name'), 'composers', ['name'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('genre_code', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_genre_code'), 'genres', ['genre_code'], unique=True)
    op.create_table('lyricists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lyricists_name'), 'lyricists', ['name'], unique=True)
    op.create_table('songs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('song_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('song_length', sa.Integer(), nullable=True),
    sa.Column('language', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_song_id'), 'songs', ['song_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('msno', sa.String(length=128), nullable=False),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('bd', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_msno'), 'users', ['msno'], unique=True)
    op.create_table('song_composer_m2m',
    sa.Column('song_id', sa.BigInteger(), nullable=False),
    sa.Column('composer_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'composer_id')
    )
    op.create_table('song_genre_m2m',
    sa.Column('song_id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'genre_id')
    )
    op.create_table('song_lyricist_m2m',
    sa.Column('song_id', sa.BigInteger(), nullable=False),
    sa.Column('lyricist_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['lyricist_id'], ['lyricists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'lyricist_id')
    )
    op.create_table('user_genre_preference_m2m',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_genre_preference_m2m')
    op.drop_table('song_lyricist_m2m')
    op.drop_table('song_genre_m2m')
    op.drop_table('song_composer_m2m')
    op.drop_index(op.f('ix_users_msno'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_songs_song_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_lyricists_name'), table_name='lyricists')
    op.drop_table('lyricists')
    op.drop_index(op.f('ix_genres_genre_code'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_composers_name'), table_name='composers')
    op.drop_table('composers')
    # ### end Alembic commands ###
