"""初始版本数据库

Revision ID: bf35f1409a44
Revises: 
Create Date: 2026-04-02 21:45:39.115922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf35f1409a44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composers_name'), 'composers', ['name'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('genre_code', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_genre_code'), 'genres', ['genre_code'], unique=True)
    op.create_table('lyricists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lyricists_name'), 'lyricists', ['name'], unique=True)
    op.create_table('songs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('song_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('song_length', sa.Integer(), nullable=True),
    sa.Column('language', sa.Float(), nullable=True),
    sa.Column('audio_object_key', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_song_id'), 'songs', ['song_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('msno', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('bd', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='genderenum'), nullable=True),
    sa.Column('registration_init_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_msno'), 'users', ['msno'], unique=True)
    op.create_table('play_counts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('song_id', sa.BigInteger(), nullable=False),
    sa.Column('total_play_count', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', name='uq_play_counts_song_id')
    )
    op.create_index(op.f('ix_play_counts_song_id'), 'play_counts', ['song_id'], unique=False)
    op.create_index('ix_play_counts_total_play_count', 'play_counts', ['total_play_count'], unique=False)
    op.create_table('play_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('song_id', sa.BigInteger(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_histories_played_at'), 'play_histories', ['played_at'], unique=False)
    op.create_index(op.f('ix_play_histories_song_id'), 'play_histories', ['song_id'], unique=False)
    op.create_index('ix_play_histories_song_played_at', 'play_histories', ['song_id', 'played_at'], unique=False)
    op.create_index(op.f('ix_play_histories_user_id'), 'play_histories', ['user_id'], unique=False)
    op.create_index('ix_play_histories_user_played_at', 'play_histories', ['user_id', 'played_at'], unique=False)
    op.create_table('song_composer_m2m',
    sa.Column('song_id', sa.BigInteger(), nullable=False),
    sa.Column('composer_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'composer_id')
    )
    op.create_table('song_genre_m2m',
    sa.Column('song_id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'genre_id')
    )
    op.create_table('song_lyricist_m2m',
    sa.Column('song_id', sa.BigInteger(), nullable=False),
    sa.Column('lyricist_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['lyricist_id'], ['lyricists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'lyricist_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('song_lyricist_m2m')
    op.drop_table('song_genre_m2m')
    op.drop_table('song_composer_m2m')
    op.drop_index('ix_play_histories_user_played_at', table_name='play_histories')
    op.drop_index(op.f('ix_play_histories_user_id'), table_name='play_histories')
    op.drop_index('ix_play_histories_song_played_at', table_name='play_histories')
    op.drop_index(op.f('ix_play_histories_song_id'), table_name='play_histories')
    op.drop_index(op.f('ix_play_histories_played_at'), table_name='play_histories')
    op.drop_table('play_histories')
    op.drop_index('ix_play_counts_total_play_count', table_name='play_counts')
    op.drop_index(op.f('ix_play_counts_song_id'), table_name='play_counts')
    op.drop_table('play_counts')
    op.drop_index(op.f('ix_users_msno'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_songs_song_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_lyricists_name'), table_name='lyricists')
    op.drop_table('lyricists')
    op.drop_index(op.f('ix_genres_genre_code'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_composers_name'), table_name='composers')
    op.drop_table('composers')
    # ### end Alembic commands ###
