"""增加热门榜复合索引

Revision ID: ec8c1eb3ec2c
Revises: 5967ac8d20d9
Create Date: 2026-04-13 11:23:52.322748

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec8c1eb3ec2c"
down_revision: Union[str, Sequence[str], None] = "5967ac8d20d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_play_counts_rank",
        "play_counts",
        ["total_play_count", "song_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_play_counts_rank", table_name="play_counts")
    # ### end Alembic commands ###
